name: Deploy Dashboard to Raspberry Pi

on:
  push:
    branches:
      - master  # Use your actual branch name here

jobs:
  deploy:
    runs-on: self-hosted  # Changed from ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          cd ~/dashboard
          git reset --hard
          git clean -fd
          git pull origin master
          docker compose down
          docker compose up -d --build
